# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'M80ImageMerger' do
  	pod ‘PureLayout’
	pod 'SVProgressHUD'
	pod 'Toast'


end

target 'M80WebViewSaver' do

	pod 'SVProgressHUD'
	pod 'Toast'


end


pre_install do |installer|
    pod_targets = installer.pod_targets.flat_map do |pod_target|
        pod_target.name == "SVProgressHUD" ? pod_target.scoped : pod_target
    end
    installer.aggregate_targets.each do |aggregate_target|
        aggregate_target.pod_targets = pod_targets.select do |pod_target|
            pod_target.target_definitions.include?(aggregate_target.target_definition)
        end
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'SVProgressHUD-Pods-M80WebViewSaver'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'SV_APP_EXTENSIONS'
            end
        end
    end
end
